import {waitProjectReady} from './project-fixture.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import http from 'node:http';import {startStudio} from '../server/index.mjs';import {runAgent} from '../server/agent.mjs';
const build=async d=>{await fs.mkdir(path.join(d,'dist/h5'),{recursive:true});await fs.writeFile(path.join(d,'dist/h5/index.html'),'<html></html>');};
for(const exhausted of [false,true])test(exhausted?'sixth verification succeeds after old three-check cap':'third verification may succeed',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'sprout-budget-')),steps=[{action:'count',selector:'.cell',value:441}],actions=[{name:'write_file',args:{path:'src/pages/index/index.css',content:'page{color:green}'}},{name:'build_preview',args:{}},...Array.from({length:exhausted?6:3},(_,i)=>({name:'verify_preview',args:{steps:steps.map(s=>({...s,selector:'.case-'+i}))}}))];let requests=0,executions=0;const model=http.createServer(async(req,res)=>{for await(const c of req){}const action=actions[requests++];res.writeHead(200,{'Content-Type':'text/event-stream'});const send=(delta,finish_reason=null)=>res.write('data: '+JSON.stringify({id:'budget',choices:[{index:0,delta,finish_reason}]})+'\n\n');send({role:'assistant'});if(action){send({tool_calls:[{index:0,id:'call-'+requests,type:'function',function:{name:action.name,arguments:JSON.stringify(action.args)}}]});send({},'tool_calls');}else{send({content:'完成'});send({},'stop');}res.end('data: [DONE]\n\n');});await new Promise(r=>model.listen(0,'127.0.0.1',r));
 const studio=await startStudio({root,port:0,production:true,seed:false,build,agent:args=>runAgent({...args,verify:async(_d,s)=>{executions++;return{state:executions===(exhausted?6:3)?'passed':'failed',error:'数量不符：实际625；期待441',steps:s,kind:'fixture-verifier'};}})});
 try{const headers={'X-Studio-Token':studio.token,'Content-Type':'application/json'},post=(url,body)=>fetch(studio.url+'/api'+url,{method:'POST',headers,body:JSON.stringify(body)});const p=await(await post('/projects',{title:'预算边界'})).json();await waitProjectReady(studio,p);await post('/settings',{provider:'custom',baseUrl:`http://127.0.0.1:${model.address().port}/v1`,model:'fixture',apiKey:'budget-fixture-only'});const response=await post(`/projects/${p.id}/run`,{prompt:'修改并检查'}),events=await response.text(),saved=await studio.store.get(p.id),task=saved.tasks.at(-1);assert.equal(executions,exhausted?6:3);assert.equal(task.verifyAttempts,exhausted?6:3);assert.equal(task.state,'completed');assert.equal(saved.revision,p.revision+1);assert.equal(saved.verification.state,'passed');assert.equal(task.executionPolicy,'continuous');}

 finally{await studio.close();model.closeAllConnections();await new Promise(r=>model.close(r));}
});
