import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import http from 'node:http';
import {spawn} from 'node:child_process';
import {chromium} from 'playwright-core';
import {Store} from '../server/store.mjs';
import {runAgent} from '../server/agent.mjs';
import {createTask,recoverTasks,exhaustedBudget,normalizeVerificationBudget,remember,checkpointBudget} from '../server/harness.mjs';
import {verifyPreview} from '../server/verify.mjs';
const progress='《活着》 当前第120页 / 共200页 进度60% 作者余华';
async function pageHtml(){
 const modules={};for(const name of await fs.readdir('templates/mini/src/vendor/qr/core'))if(name.endsWith('.js'))modules['./'+name.slice(0,-3)]=await fs.readFile('templates/mini/src/vendor/qr/core/'+name,'utf8');const code=Object.entries(modules).map(([name,src])=>JSON.stringify(name)+':function(require,module,exports){'+src+'}').join(',');
 return `<html><head></head><body><section id="book-form"><span class="label">书名</span><input value="INPUT_VALUE_MUST_NOT_LEAK"><span class="label">作者（可选）</span><input value="ANOTHER_PRIVATE_VALUE"></section><section id="book-detail"><button class="btn-ghost" onclick="document.querySelector('#output').innerHTML='';document.querySelector('#status').textContent='书架'">返回书架</button><button class="btn-ghost" id="make-progress" onclick="makeQr()">生成进度二维码</button></section><div id="status">准备好</div><div id="output"></div><script>const modules={${code}},cache={};function require(id){if(cache[id])return cache[id].exports;const m={exports:{}};cache[id]=m;modules[id](require,m,m.exports);return m.exports}const QR=require('./index');function makeQr(){const q=new QR(-1,0);q.addData(encodeURIComponent(${JSON.stringify(progress)}).replace(/%([0-9a-f]{2})/gi,(_,h)=>String.fromCharCode(parseInt(h,16))));q.make();const n=q.getModuleCount(),s=(n+8)*3,c=document.createElement('canvas');c.className='qr-box';c.width=c.height=s;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,s,s);ctx.fillStyle='black';for(let y=0;y<n;y++)for(let x=0;x<n;x++)if(q.isDark(y,x))ctx.fillRect((x+4)*3,(y+4)*3,3,3);document.querySelector('#output').replaceChildren(c);}</script></body></html>`;
}
const action=(name,args={})=>({name,args});
const verify=steps=>action('verify_preview',{steps});
const qrSteps=selector=>[{action:'click',selector},{action:'count',selector:'.qr-box',value:1},{action:'qr',selector:'.qr-box',value:progress}];
async function agentFixture(decide,{html,injectVerify,seedTask,existing,testSessionOptions,buildHook,externalSignal,checkpointHook}={}){
 const root=existing?.store.root||await fs.mkdtemp(path.join(os.tmpdir(),'sprout-continuous-')),store=existing?.store||new Store(root);await store.init();const project=existing?.project||await store.create('读书助理'),task=await createTask(store,project,'制作读书记录小程序',existing?.task);if(seedTask)Object.assign(task,seedTask);project.memory.constraints='保留中文书名';await store.save(project);
 let requests=0,builds=0;const payloads=[],events=[];const model=http.createServer(async(req,res)=>{try{let raw='';for await(const c of req)raw+=c;const body=JSON.parse(raw);payloads.push(body);const summary=!body.tools?.length;const next=summary?null:decide(body,requests++);res.writeHead(200,{'Content-Type':'text/event-stream'});const send=(delta,finish_reason=null)=>res.write('data: '+JSON.stringify({id:'v2',choices:[{index:0,delta,finish_reason}]})+'\n\n');send({role:'assistant'});if(next){send({tool_calls:[{index:0,id:'call-'+requests,type:'function',function:{name:next.name,arguments:JSON.stringify(next.args)}}]});send({},'tool_calls');}else{send({content:summary?'原始需求：制作读书记录小程序。最近错误：计算结果错误。草稿未验收，必须重新构建检查。':'完成'});send({},'stop');}res.end('data: [DONE]\n\n');}catch(e){res.writeHead(500);res.end(e.stack);}});await new Promise(r=>model.listen(0,'127.0.0.1',r));
 const build=async (d,options)=>{builds++;if(buildHook)await buildHook(d,options);await fs.mkdir(path.join(d,'dist/h5'),{recursive:true});await fs.writeFile(path.join(d,'dist/h5/index.html'),html||await pageHtml());};
 try{const output=await runAgent({store,project,task,prompt:'制作读书记录小程序',config:{baseUrl:`http://127.0.0.1:${model.address().port}/v1`,model:'fixture',apiKey:'v2-fixture-only'},signal:externalSignal||AbortSignal.timeout(90000),emit:e=>events.push(e),onBudgetCheckpoint:checkpointHook?()=>checkpointHook({store,project,task}):undefined,testSessionOptions,build,...(injectVerify?{verify:injectVerify}:{})});return {output,task,requests,builds,payloads,events,store,project};}catch(error){task.state='failed';task.resumable=true;await store.save(project);return {error,task,requests,builds,payloads,events,store,project};}finally{model.closeAllConnections();await new Promise(r=>model.close(r));}
}
function start(n){return n===0?action('write_file',{path:'src/pages/index/index.css',content:'page{color:green}'}):n===1?action('build_preview'):undefined;}
function feedback(body){const text=body.messages.filter(m=>m.role==='tool').at(-1)?.content;return typeof text==='string'?JSON.parse(text):null;}


test('E9 rejects a different same-project session before append; legitimate successive native resumes preserve binding',async()=>{
 const one=await agentFixture((_b,n)=>[start(0),start(1),null][n],{injectVerify:async()=>({state:'passed'})});assert.equal(one.error.code,'no-progress');const own=one.task.sessionFile;
 const other=await agentFixture((_b,n)=>[action('write_file',{path:'src/pages/index/index.css',content:'page{color:blue}'}),null][n],{existing:{store:one.store,project:one.project}});const wrong=await one.store.taskPath(one.project.id,'sessions',other.task.sessionFile),before=await fs.readFile(wrong,'utf8');one.task.sessionFile=other.task.sessionFile;
 const rejected=await agentFixture(()=>null,{existing:one});assert.equal(rejected.error.code,'session-binding-mismatch');assert.equal(await fs.readFile(wrong,'utf8'),before);
 one.task.sessionFile=own;const again=await agentFixture((_b,n)=>n===0?action('read_file',{path:'src/pages/index/index.css'}):null,{existing:one});assert.equal(again.error.code,'no-progress');assert.equal(again.task.recoveryMode,'native-session-and-draft');const final=await agentFixture((_b,n)=>[start(1),verify([{action:'text',selector:'#status',value:'准备好'}]),null][n],{existing:again,injectVerify:async(_d,steps)=>({state:'passed',steps})});assert.ifError(final.error);assert.equal(final.task.sessionFile,own);assert.equal(final.output.revision,1);
});
test('E12 continuous same-session identical build/business/static failures reuse evidence then pause; new diagnosis and changed source can succeed',async()=>{
 const build=await agentFixture((_b,n)=>n===0?start(0):start(1),{buildHook:async()=>{throw new Error('same compiler fault');}});assert.equal(build.error.code,'no-progress');assert.equal(build.builds,1);assert.equal(build.requests,4);
 let actual=0;const steps=[{action:'text',selector:'#status',value:'准备好'}],failed=await agentFixture((_b,n)=>n<2?start(n):verify(steps),{injectVerify:async()=>{actual++;return {state:'failed',error:'same business fault'};}});assert.equal(failed.error.code,'no-progress');assert.equal(actual,1);assert.equal(failed.requests,5);
 const invalid=await agentFixture((_b,n)=>n<2?start(n):verify([{action:'click',selector:'#status'}]));assert.equal(invalid.error.code,'no-progress');assert.equal(invalid.task.verificationRuns,0);assert.equal(invalid.task.planCorrectionAttempts,1);
 let calls=0;const actions=[start(0),start(1),verify(steps),verify(steps),action('read_file',{path:'src/pages/index/index.jsx'}),verify(steps),null],progress=await agentFixture((_b,n)=>actions[n],{injectVerify:async(_d,steps)=>({state:++calls===2?'passed':'failed',steps,error:calls===2?undefined:'same business fault'})});assert.ifError(progress.error);assert.equal(calls,2);
});
async function killedRequirementWindow(window){
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'sprout-cover-kill-'));let requests=0;const model=http.createServer(async(req,res)=>{for await(const c of req){}requests++;const next=action('read_requirements',{section:'changes',index:0,offset:0});res.writeHead(200,{'Content-Type':'text/event-stream'});res.end('data: '+JSON.stringify({id:'kill',choices:[{index:0,delta:{role:'assistant',tool_calls:[{index:0,id:'page-call',type:'function',function:{name:next.name,arguments:JSON.stringify(next.args)}}]},finish_reason:'tool_calls'}]})+'\n\ndata: [DONE]\n\n');});await new Promise(r=>model.listen(0,'127.0.0.1',r));
 const source=window==='page'?'历史约束'.repeat(13000):'初始历史原文必须装载';const hook=window==='page'?'beforeRequirementResult':'beforeInitialPrompt';const code=`import fs from 'node:fs/promises';import {Store} from ${JSON.stringify(new URL('../server/store.mjs',import.meta.url).href)};import {createTask,remember} from ${JSON.stringify(new URL('../server/harness.mjs',import.meta.url).href)};import {runAgent} from ${JSON.stringify(new URL('../server/agent.mjs',import.meta.url).href)};const store=new Store(${JSON.stringify(root)});await store.init();const project=await store.create('读书助理');project.memory.constraints='保留中文书名';remember(project,${JSON.stringify(source)},'');const task=await createTask(store,project,'制作读书记录小程序');await runAgent({store,project,task,prompt:task.prompt,config:{baseUrl:'http://127.0.0.1:${model.address().port}/v1',model:'fixture',apiKey:'fixture-only'},signal:new AbortController().signal,emit:()=>{},testSessionOptions:{${hook}:async()=>{console.log('WINDOW_READY');await new Promise(()=>{});}}});`;
 const scriptFile=path.join(root,'kill-window.mjs');await fs.writeFile(scriptFile,code);const child=spawn(process.execPath,[scriptFile],{windowsHide:true,stdio:['ignore','pipe','pipe']});let stderr='';child.stderr.on('data',c=>stderr+=c);
 try{await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('kill-window timeout '+stderr)),20000);let output='';child.stdout.on('data',c=>{output+=c;if(output.includes('WINDOW_READY')){clearTimeout(timer);resolve();}});child.once('exit',code=>{clearTimeout(timer);reject(new Error('premature '+code+' '+stderr));});});const store=new Store(root),project=await store.get((await store.list())[0].id),task=project.tasks.at(-1);assert.ok(task.pendingRequirements.length);assert.equal(requests,window==='page'?1:0);if(window==='page'){assert.ok(task.requirementPageInFlight);const native=await fs.readFile(await store.taskPath(project.id,'sessions',task.sessionFile),'utf8');assert.ok(!native.trim().split('\n').map(e=>JSON.parse(e)).some(e=>e.message?.role==='toolResult'&&e.message?.toolName==='read_requirements'));}await new Promise(r=>{child.once('exit',r);child.kill('SIGKILL');});await recoverTasks(store);const saved=await store.get(project.id),prior=saved.tasks.at(-1);prior.pendingRequirements=[];await store.save(saved);return {store,project:saved,task:prior,source};}finally{if(child.exitCode===null)child.kill('SIGKILL');model.closeAllConnections();await new Promise(r=>model.close(r));}
}
test('E10 hard kill after page reservation but before native result forces actual original pages to be read again',async()=>{
 const prior=await killedRequirementWindow('page'),steps=[{action:'text',selector:'#status',value:'准备好'}],pages=Array.from({length:Math.ceil(prior.source.length/12000)},(_,i)=>action('read_requirements',{section:'changes',index:0,offset:i*12000})),actions=[start(0),start(1),verify(steps),null,...pages,null];const f=await agentFixture((_b,n)=>actions[n],{existing:prior,injectVerify:async(_d,steps)=>({state:'passed',steps})});assert.ifError(f.error);assert.ok(f.task.repairPrompts>=1);assert.equal(f.task.pendingRequirements.length,0);assert.equal(f.task.recoveryMode,'native-session-and-draft');assert.equal(f.output.revision,1);
});
test('E10 hard kill before initial history user-message persistence rebuilds honestly and loads original history',async()=>{
 const prior=await killedRequirementWindow('initial');const f=await agentFixture((_b,n)=>[start(0),start(1),verify([{action:'text',selector:'#status',value:'准备好'}]),null][n],{existing:prior,injectVerify:async(_d,steps)=>({state:'passed',steps})});assert.ifError(f.error);assert.equal(f.task.recoveryMode,'initialization-interrupted-context-rebuilt');assert.ok(f.payloads[0].messages.some(m=>JSON.stringify(m.content).includes(prior.source)));assert.equal(f.task.pendingRequirements.length,0);
});

test('E14 build-required never caches across successful compile, same plan really runs and legacy precondition cache is cleared',async()=>{
 const steps=[{action:'text',selector:'#status',value:'准备好'}],actions=[start(0),verify(steps),start(1),verify(steps),verify(steps),null];const f=await agentFixture((_b,n)=>actions[n],{seedTask:{toolFailures:[{key:'legacy-precondition',output:[{kind:'build-required'}]}]}});assert.ifError(f.error);assert.equal(f.task.verificationRuns,2);assert.equal(f.output.verification.state,'passed');assert.equal(f.output.verification.kind,'real-browser');assert.ok(!f.task.toolFailures.some(c=>c.key==='legacy-precondition'));assert.equal(f.output.revision,1);
});
test('E15 repeated invalid write, missing read and invalid requirement page pause within one PI tool chain; corrected params can deliver',async()=>{
 const bad=[action('write_file',{path:'src/pages/index/index.jsx',content:'document.body'}),action('write_file',{path:'src/../../outside.jsx',content:'x'}),action('read_file',{path:'src/components/missing.jsx'}),action('read_requirements',{section:'changes',index:999,offset:0})];
 for(const operation of bad){const f=await agentFixture(()=>operation);assert.equal(f.error.code,'no-progress');assert.equal(f.requests,3);assert.equal(f.task.toolFailures.length,1);assert.equal(f.task.toolFailures[0].output[0].kind,'tool-error');assert.equal(f.project.revision,0);}
 const actions=[bad[0],start(0),start(1),verify([{action:'text',selector:'#status',value:'准备好'}]),null],corrected=await agentFixture((_b,n)=>actions[n],{injectVerify:async(_d,steps)=>({state:'passed',steps})});assert.ifError(corrected.error);assert.equal(corrected.output.revision,1);
});
test('E15 ordinary thrown error redacts secrets while user stop and checkpoint failure still escape',async()=>{
 const secretRead=await agentFixture(()=>action('read_file',{path:'src/components/v2-fixture-only.jsx'}));assert.equal(secretRead.error.code,'no-progress');assert.doesNotMatch(JSON.stringify(secretRead.task.toolFailures),/v2-fixture-only/);
 const controller=new AbortController(),stopped=await agentFixture((_b,n)=>n===0?start(0):start(1),{externalSignal:controller.signal,buildHook:async(_d,{signal})=>{controller.abort(new Error('user-stop'));signal.throwIfAborted();}});assert.match(stopped.error.message,/user-stop/);assert.ok(!stopped.task.toolFailures?.length);let checkpoints=0;const blocked=await agentFixture(()=>start(0),{checkpointHook:async({store,project,task})=>{if(task.toolCalls===1&&++checkpoints===2)throw new Error('fixture disk failure');await store.save(project);}});assert.equal(blocked.error.code,'checkpoint-failed');assert.ok(!blocked.task.toolFailures?.length);assert.equal(blocked.project.revision,0);
});
