import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import http from 'node:http';
import {chromium} from 'playwright-core';
import {Store} from '../server/store.mjs';
import {runAgent} from '../server/agent.mjs';
import {createTask,recoverTasks,exhaustedBudget,normalizeVerificationBudget,remember,checkpointBudget} from '../server/harness.mjs';
import {verifyPreview} from '../server/verify.mjs';
const progress='《活着》 当前第120页 / 共200页 进度60% 作者余华';
async function pageHtml(){
 const modules={};for(const name of await fs.readdir('templates/mini/src/vendor/qr/core'))if(name.endsWith('.js'))modules['./'+name.slice(0,-3)]=await fs.readFile('templates/mini/src/vendor/qr/core/'+name,'utf8');const code=Object.entries(modules).map(([name,src])=>JSON.stringify(name)+':function(require,module,exports){'+src+'}').join(',');
 return `<html><head></head><body><section id="book-form"><span class="label">书名</span><input value="INPUT_VALUE_MUST_NOT_LEAK"><span class="label">作者（可选）</span><input value="ANOTHER_PRIVATE_VALUE"></section><section id="book-detail"><button class="btn-ghost" onclick="document.querySelector('#output').innerHTML='';document.querySelector('#status').textContent='书架'">返回书架</button><button class="btn-ghost" id="make-progress" onclick="makeQr()">生成进度二维码</button></section><div id="status">准备好</div><div id="output"></div><script>const modules={${code}},cache={};function require(id){if(cache[id])return cache[id].exports;const m={exports:{}};cache[id]=m;modules[id](require,m,m.exports);return m.exports}const QR=require('./index');function makeQr(){const q=new QR(-1,0);q.addData(encodeURIComponent(${JSON.stringify(progress)}).replace(/%([0-9a-f]{2})/gi,(_,h)=>String.fromCharCode(parseInt(h,16))));q.make();const n=q.getModuleCount(),s=(n+8)*3,c=document.createElement('canvas');c.className='qr-box';c.width=c.height=s;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,s,s);ctx.fillStyle='black';for(let y=0;y<n;y++)for(let x=0;x<n;x++)if(q.isDark(y,x))ctx.fillRect((x+4)*3,(y+4)*3,3,3);document.querySelector('#output').replaceChildren(c);}</script></body></html>`;
}
const action=(name,args={})=>({name,args});
const verify=steps=>action('verify_preview',{steps});
const qrSteps=selector=>[{action:'click',selector},{action:'count',selector:'.qr-box',value:1},{action:'qr',selector:'.qr-box',value:progress}];
async function agentFixture(decide,{html,injectVerify,seedTask,existing,testSessionOptions,buildHook,externalSignal}={}){
 const root=existing?.store.root||await fs.mkdtemp(path.join(os.tmpdir(),'sprout-continuous-')),store=existing?.store||new Store(root);await store.init();const project=existing?.project||await store.create('读书助理'),task=await createTask(store,project,'制作读书记录小程序',existing?.task);if(seedTask)Object.assign(task,seedTask);project.memory.constraints='保留中文书名';await store.save(project);
 let requests=0,builds=0;const payloads=[],events=[];const model=http.createServer(async(req,res)=>{try{let raw='';for await(const c of req)raw+=c;const body=JSON.parse(raw);payloads.push(body);const summary=!body.tools?.length;const next=summary?null:decide(body,requests++);res.writeHead(200,{'Content-Type':'text/event-stream'});const send=(delta,finish_reason=null)=>res.write('data: '+JSON.stringify({id:'v2',choices:[{index:0,delta,finish_reason}]})+'\n\n');send({role:'assistant'});if(next){send({tool_calls:[{index:0,id:'call-'+requests,type:'function',function:{name:next.name,arguments:JSON.stringify(next.args)}}]});send({},'tool_calls');}else{send({content:summary?'原始需求：制作读书记录小程序。最近错误：计算结果错误。草稿未验收，必须重新构建检查。':'完成'});send({},'stop');}res.end('data: [DONE]\n\n');}catch(e){res.writeHead(500);res.end(e.stack);}});await new Promise(r=>model.listen(0,'127.0.0.1',r));
 const build=async (d,options)=>{builds++;if(buildHook)await buildHook(d,options);await fs.mkdir(path.join(d,'dist/h5'),{recursive:true});await fs.writeFile(path.join(d,'dist/h5/index.html'),html||await pageHtml());};
 try{const output=await runAgent({store,project,task,prompt:'制作读书记录小程序',config:{baseUrl:`http://127.0.0.1:${model.address().port}/v1`,model:'fixture',apiKey:'v2-fixture-only'},signal:externalSignal||AbortSignal.timeout(90000),emit:e=>events.push(e),testSessionOptions,build,...(injectVerify?{verify:injectVerify}:{})});return {output,task,requests,builds,payloads,events,store,project};}catch(error){task.state='failed';task.resumable=true;await store.save(project);return {error,task,requests,builds,payloads,events,store,project};}finally{model.closeAllConnections();await new Promise(r=>model.close(r));}
}
function start(n){return n===0?action('write_file',{path:'src/pages/index/index.css',content:'page{color:green}'}):n===1?action('build_preview'):undefined;}
function feedback(body){const text=body.messages.filter(m=>m.role==='tool').at(-1)?.content;return typeof text==='string'?JSON.parse(text):null;}

test('continuous task makes progress beyond old tools/builds/verifications/host prompts/resumes/time without fake remaining',async()=>{
 const steps=[{action:'text',selector:'#status',value:'准备好'}],actions=[start(0),...Array.from({length:45},()=>action('list_files')),...Array.from({length:4},()=>start(1)),...Array.from({length:6},(_,i)=>verify([{...steps[0],selector:'#case-'+i}])),null,...Array.from({length:4},(_,i)=>[action('write_file',{path:'src/pages/index/index.css',content:'page{color:rgb('+i+',0,0)}'}),null]).flat(),action('write_file',{path:'src/pages/index/index.css',content:'page{color:green}'}),start(1),verify(steps),null];let calls=0;
 const f=await agentFixture((body,n)=>{const last=body.messages.filter(m=>m.role==='tool').at(-1)?.content;if(last?.startsWith('{')&&last.includes('"usage"'))assert.doesNotMatch(last,/remaining|budget/);return actions[n];},{seedTask:{toolCalls:40,buildAttempts:3,verifyAttempts:6,verificationRuns:6,businessVerifyAttempts:3,repairPrompts:3,budgetUsedMs:700000,attempts:5},injectVerify:async(_d,steps)=>({state:++calls===7?'passed':'failed',steps,error:calls===7?undefined:'计算结果错误'})});
 assert.ifError(f.error);assert.equal(f.output.revision,1);assert.ok(f.task.toolCalls>80);assert.ok(f.task.buildAttempts>7);assert.equal(f.task.verifyAttempts,13);assert.ok(f.task.repairPrompts>6);assert.ok(f.task.budgetUsedMs>700000);assert.equal(f.task.executionPolicy,'continuous');assert.equal(f.task.usage.cost,'unknown');
 const legacyProject=await f.store.create('历史恢复');let previous=await createTask(f.store,legacyProject,'制作');previous.state='stopped';previous.resumable=false;previous.reason='verification-budget-exhausted';for(let n=0;n<5;n++){previous=await createTask(f.store,legacyProject,'继续',previous);previous.state='stopped';}assert.ok(previous.attempts>3);assert.equal(exhaustedBudget(previous),false);
});
test('stop retains exact draft/session; resume opens native context, ignores historical error and forces fresh build/check',async()=>{
 const controller=new AbortController();const stop=await agentFixture((_b,n)=>n===0?start(0):n===1?start(1):null,{externalSignal:controller.signal,buildHook:async(_d,{signal})=>{controller.abort(new Error('user-stop'));signal.throwIfAborted();}});
 // Same-source build failures pause after actionable feedback, preserving the draft.
 assert.match(stop.error.message,/user-stop/);assert.ok(stop.task.draftRef);assert.ok(stop.task.sessionFile);const ref=stop.task.sessionFile,draft=await stop.store.taskPath(stop.project.id,'drafts',stop.task.draftRef);assert.match(await fs.readFile(path.join(draft,'src/pages/index/index.css'),'utf8'),/green/);
 const file=await stop.store.taskPath(stop.project.id,'sessions',ref);await fs.appendFile(file,JSON.stringify({type:'message',id:'historic-error',parentId:null,timestamp:new Date().toISOString(),message:{role:'assistant',content:[],api:'openai-completions',provider:'sprout-model',model:'fixture',usage:{input:0,output:0,totalTokens:0,cost:{}},stopReason:'error',errorMessage:'historical provider failure',timestamp:Date.now()}})+'\n');
 const resumed=await agentFixture((_b,n)=>n===0?action('read_file',{path:'src/pages/index/index.css'}):n===1?start(1):n===2?verify([{action:'text',selector:'#status',value:'准备好'}]):null,{existing:stop,injectVerify:async(_d,steps)=>({state:'passed',steps})});assert.ifError(resumed.error);assert.equal(resumed.output.revision,1);assert.equal(resumed.task.sessionFile,ref);assert.equal(resumed.task.recoveryMode,'native-session-and-draft');assert.equal(resumed.builds,1);assert.match(JSON.stringify(resumed.payloads[1]),/page\{color:green/);
});
test('native PI compact uses real summary request and persisted compaction before continued verified delivery',async()=>{
 const steps=[{action:'text',selector:'#status',value:'准备好'}];let checks=0;const f=await agentFixture((_b,n)=>[start(0),start(1),verify(steps),null,action('write_file',{path:'src/pages/index/index.css',content:'page{color:blue}'}),start(1),verify(steps),null][n],{testSessionOptions:{compactAfterPrompt:true,keepRecentTokens:0},injectVerify:async(_d,steps)=>({state:++checks===1?'failed':'passed',steps,error:checks===1?'计算结果错误':undefined})});assert.ifError(f.error);const entries=(await fs.readFile(await f.store.taskPath(f.project.id,'sessions',f.task.sessionFile),'utf8')).trim().split('\n').map(x=>JSON.parse(x));assert.equal(f.task.compaction.reason,'manual');assert.equal(f.task.compaction.state,'completed');assert.ok(f.events.some(e=>e.text==='正在压缩会话上下文，保留需求和最近反馈'));assert.ok(entries.some(e=>e.type==='compaction'&&e.summary.includes('最近错误：计算结果错误')));const summaryRequest=f.payloads.find(p=>!p.tools?.length);assert.ok(summaryRequest);assert.match(JSON.stringify(summaryRequest),/制作读书记录小程序/);assert.match(JSON.stringify(summaryRequest),/计算结果错误/);assert.match(JSON.stringify(f.payloads.at(-1)),/原始需求：制作读书记录小程序/);assert.match(JSON.stringify(f.payloads.at(-1)),/保留中文书名/);assert.equal(f.output.verification.state,'passed');
});
test('requirement history is retained beyond old capacity and paged coverage blocks delivery until complete',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'sprout-requirements-')),store=new Store(root);await store.init();const project=await store.create('分页');for(let i=0;i<5;i++)remember(project,'约束'+i+'中'.repeat(11000),'');await store.save(project);assert.ok(JSON.stringify(project.memory).length>48000);
 const pages=Array.from({length:5},(_,index)=>action('read_requirements',{section:'changes',index,offset:0})),actions=[start(0),start(1),verify([{action:'text',selector:'#status',value:'准备好'}]),null,...pages,null];const task=await createTask(store,project,'制作');task.state='stopped';const f=await agentFixture((_b,n)=>actions[n],{existing:{store,project,task},injectVerify:async(_d,steps)=>({state:'passed',steps})});assert.ifError(f.error);assert.equal(f.task.pendingRequirements.length,0);assert.equal(project.memory.changes.length,5);assert.ok(f.task.requirementsDigest);assert.ok(f.payloads.some(p=>JSON.stringify(p).includes('历史需求未全部装入')));
});
test('controlled recovery paths reject traversal and linked drafts; legacy budget state is explicitly resumable',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'sprout-path-')),store=new Store(root);await store.init();const project=await store.create('路径');await assert.rejects(store.taskPath(project.id,'drafts','../other'),/引用无效/);const draft=await store.draft(project.id);await fs.symlink(os.tmpdir(),path.join(draft,'escape'),process.platform==='win32'?'junction':'dir');await assert.rejects(store.taskPath(project.id,'drafts',path.basename(draft)),/链接/);project.tasks=[{state:'failed',resumable:false,reason:'verification-budget-exhausted'}];assert.equal(store.public(project).tasks[0].resumable,true);assert.equal(project.tasks[0].resumable,false);
});
test('union CSS remains scoped when resolving editable children',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'sprout-union-'));await fs.mkdir(path.join(root,'dist/h5'),{recursive:true});await fs.writeFile(path.join(root,'dist/h5/index.html'),'<html><head></head><body><div id="form"><input id="name" oninput="document.querySelector(\'#status\').textContent=this.value"></div><div id="status">ready</div></body></html>');const steps=[{action:'fill',selector:'#form,#missing',value:'中文书名'},{action:'text',selector:'#status',value:'中文书名'}];assert.equal((await verifyPreview(root,steps)).state,'passed');await fs.writeFile(path.join(root,'dist/h5/index.html'),'<html><head></head><body><div id="form"><input aria-label="书名"><input aria-label="作者"></div><div id="status">ready</div></body></html>');const fail=await verifyPreview(root,steps);assert.equal(fail.failureType,'plan');assert.equal(fail.matchCount,2);assert.equal(fail.selector,'#form,#missing');assert.equal(fail.targetContext,'editable-child');
});

test('static invalid plans and unknown injected classification remain honest usage facts without a free-plan escape',async()=>{
 const actions=[start(0),start(1),verify([{action:'click',selector:'#x'}]),verify([{action:'click',selector:'#y'}]),verify([{action:'text',selector:'#status',value:'准备好'}]),null];const f=await agentFixture((_b,n)=>actions[n],{injectVerify:async(_d,steps)=>({state:'passed',steps})});assert.ifError(f.error);assert.equal(f.task.planCorrectionAttempts,2);assert.equal(f.task.verificationRuns,1);assert.equal(f.task.businessVerifyAttempts,1);
 const spoof=await agentFixture((_b,n)=>[start(0),start(1),verify([{action:'text',selector:'#status',value:'准备好'}]),null][n],{injectVerify:async()=>({state:'failed',failureType:'plan',error:'spoof plan'})});assert.equal(spoof.error.code,'no-progress');assert.equal(spoof.task.businessVerifyAttempts,1);assert.equal(spoof.task.planCorrectionAttempts,0);
});

test('new source-reading evidence allows multiple host rounds; identical reading evidence pauses honestly',async()=>{
 const read=name=>action('read_file',{path:name}),steps=[{action:'text',selector:'#status',value:'准备好'}],actions=[read('src/pages/index/index.jsx'),null,read('src/pages/index/index.css'),null,read('src/app.css'),null,action('list_files'),null,start(0),start(1),verify(steps),null];const f=await agentFixture((_b,n)=>actions[n],{injectVerify:async(_d,steps)=>({state:'passed',steps})});assert.ifError(f.error);assert.equal(f.task.repairPrompts,4);assert.ok(f.task.progressEvidence.length>=7);
 const repeated=await agentFixture((_b,n)=>[read('src/pages/index/index.jsx'),null,read('src/pages/index/index.jsx'),null][n]);assert.equal(repeated.error.code,'no-progress');assert.equal(repeated.task.progressEvidence.length,1);assert.ok(repeated.task.draftRef);
});

test('final supplier failure preserves draft and reports its source without borrowing an old plan failure',async()=>{
 const f=await agentFixture(()=>{throw new Error('fixture provider unavailable');},{seedTask:{lastVerification:{state:'failed',failureType:'plan',error:'old selector'}}});assert.equal(f.error.code,'provider-unavailable');assert.equal(f.error.failureType,'external');assert.equal(f.requests,2);assert.ok(f.task.draftRef);assert.equal(f.task.lastVerification.failureType,'plan');assert.equal(f.project.revision,0);
});
