import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {startStudio} from '../server/index.mjs';
import {createTask} from '../server/harness.mjs';
test('desktop close fences new mutations and drains storage accepted before source lookup and rename',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'sprout-close-'));const studio=await startStudio({root,port:0,production:true,seed:false,build:async d=>{await fs.mkdir(path.join(d,'dist/h5'),{recursive:true});await fs.writeFile(path.join(d,'dist/h5/index.html'),'<html><head></head></html>');}});const headers={'X-Studio-Token':studio.token,'Content-Type':'application/json'},post=(url,body)=>fetch(studio.url+'/api'+url,{method:'POST',headers,body:JSON.stringify(body)});let releaseGet,releaseRename;const originalRename=fs.rename;
 try{const p=await(await post('/projects',{title:'关闭保存边界'})).json();const get=studio.store.get.bind(studio.store);let enteredGet;const getGate=new Promise(r=>enteredGet=r),getRelease=new Promise(r=>releaseGet=r);studio.store.get=async id=>{enteredGet();await getRelease;return get(id);};let enteredRename;const renameGate=new Promise(r=>enteredRename=r),renameRelease=new Promise(r=>releaseRename=r);fs.rename=async(from,to)=>{if(to===path.join(root,'projects',p.id,'storage.json')){enteredRename();await renameRelease;}return originalRename(from,to);};const accepted=post(`/projects/${p.id}/storage`,{values:{sum:'9'}});await getGate;let closed=false;const close=studio.close().then(()=>{closed=true;});assert.equal((await post(`/projects/${p.id}/storage`,{values:{sum:'100'}})).status,503);await new Promise(r=>setTimeout(r,20));assert.equal(closed,false);releaseGet();await renameGate;await new Promise(r=>setTimeout(r,20));assert.equal(closed,false);releaseRename();await accepted;await close;assert.deepEqual(JSON.parse(await fs.readFile(path.join(root,'projects',p.id,'storage.json'),'utf8')),{sum:'9'});}finally{releaseGet?.();releaseRename?.();fs.rename=originalRename;await studio.close();}
});
test('close during resume source digest prevents late job registration',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'sprout-resume-close-'));let agentCalls=0;const studio=await startStudio({root,port:0,production:true,seed:false,build:async d=>{await fs.mkdir(path.join(d,'dist/h5'),{recursive:true});await fs.writeFile(path.join(d,'dist/h5/index.html'),'<html></html>');},agent:async({project})=>{agentCalls++;return project;}});const headers={'X-Studio-Token':studio.token,'Content-Type':'application/json'},post=(url,body)=>fetch(studio.url+'/api'+url,{method:'POST',headers,body:JSON.stringify(body)});const readdir=fs.readdir;let release;
 try{const p=await(await post('/projects',{title:'恢复关闭边界'})).json();await post('/settings',{baseUrl:'http://localhost',model:'mock',apiKey:'isolated-fixture'});const project=await studio.store.get(p.id),task=await createTask(studio.store,project,'继续未完成任务');task.state='interrupted';await studio.store.save(project);let entered;const gate=new Promise(r=>entered=r),resume=new Promise(r=>release=r),revision=path.join(studio.store.dir(p.id),'revisions',String(project.revision));fs.readdir=async(dir,...args)=>{if(dir===path.join(revision,'src')){entered();await resume;}return readdir(dir,...args);};const request=post(`/projects/${p.id}/run`,{resumeTaskId:task.id});await gate;const close=studio.close();release();const response=await request;assert.equal(response.status,400);assert.match(await response.text(),/正在关闭/);await close;assert.equal(agentCalls,0);assert.equal((await studio.store.get(p.id)).tasks.length,1);}finally{release?.();fs.readdir=readdir;await studio.close();}
});
