import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {Store,writeSource,readSources} from '../server/store.mjs';
import {remember,memoryContext,createTask,recoverTasks,sourceDigest,LIMITS} from '../server/harness.mjs';
import {startStudio} from '../server/index.mjs';
const fakeBuild=async d=>{await fs.mkdir(path.join(d,'dist/h5'),{recursive:true});await fs.writeFile(path.join(d,'dist/h5/index.html'),'<html><head></head></html>');};
async function fresh(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'sprout-harness-'));const s=new Store(root);await s.init();return s;}
test('M1 full history migration, corrections, secret removal, restart and rollback policy',async()=>{
 const s=await fresh(),p=await s.create('清单');delete p.memory;p.messages=[{role:'user',text:'长期：离线保存且中文',time:1},...Array.from({length:14},(_,i)=>({role:'user',text:'变更 '+i,time:i+2}))];await s.save(p);
 assert.match(memoryContext(p),/离线保存且中文/);remember(p,'不要保存 secret-test-key','secret-test-key');assert.doesNotMatch(memoryContext(p),/secret-test-key/);
 p.memory.constraints='用户修正：不联网';const d=await s.draft(p.id);await fakeBuild(d);await s.commit(p,d,'first');const first=p.versions[0];p.memory.constraints='用户修正：不收集身份';await s.save(p);const restarted=await new Store(s.root).get(p.id);assert.equal(restarted.memory.constraints,'用户修正：不收集身份');const rollback=await s.draft(p.id,first.files);await fakeBuild(rollback);await s.commit(restarted,rollback,'rollback');assert.equal(restarted.memory.constraints,'用户修正：不收集身份');assert.equal(first.memory.constraints,'用户修正：不联网');
 p.memory.constraints='x'.repeat(LIMITS.memoryChars);assert.throws(()=>memoryContext(p),/整理/);assert.equal(p.memory.constraints.length,LIMITS.memoryChars);
});
test('M2 restart is interrupted, retry capped and source mismatch detectable',async()=>{
 const s=await fresh(),p=await s.create('恢复');const t=await createTask(s,p,'做清单');await recoverTasks(s);assert.equal((await s.get(p.id)).tasks[0].state,'interrupted');assert.equal(await sourceDigest(s,p),t.sourceDigest);await writeSource(path.join(s.dir(p.id),'current'),'src/pages/index/index.css','page{color:red}');assert.notEqual(await sourceDigest(s,p),t.sourceDigest);await assert.rejects(createTask(s,p,'继续',{attempts:3}),/上限/);
});
async function waitFor(fn){for(let i=0;i<100;i++){const value=await fn();if(value)return value;await new Promise(r=>setTimeout(r,30));}throw new Error('wait timed out');}
test('M2 HTTP disconnect continues, explicit stop persists, resume checks code and closure interrupts',async()=>{
 const s=await fresh();let release,mode='wait',observedPrompt='';const agent=async({project,signal,emit,store,prompt})=>{observedPrompt=prompt;emit({type:'status',text:'执行中'});if(mode==='instant')return project;await new Promise((resolve,reject)=>{release=resolve;signal.addEventListener('abort',()=>reject(signal.reason),{once:true});});await store.save(project);return project;};
 let studio=await startStudio({root:s.root,port:0,production:true,seed:false,build:fakeBuild,agent});let headers={'X-Studio-Token':studio.token,'Content-Type':'application/json'};const call=(url,body)=>fetch(studio.url+'/api'+url,{method:'POST',headers,body:JSON.stringify(body)});const p=await(await call('/projects',{title:'任务'})).json();await call('/settings',{baseUrl:'http://localhost',model:'mock',apiKey:'test-key-only'});
 const run=await call(`/projects/${p.id}/run`,{prompt:'做清单'});await run.body.cancel();await waitFor(async()=>release);assert.equal((await s.get(p.id)).tasks.at(-1).state,'running');assert.equal((await fetch(studio.url+`/api/projects/${p.id}/memory`,{method:'PUT',headers,body:JSON.stringify({goal:'x',constraints:'',changes:[]})})).status,400);release();await waitFor(async()=> (await s.get(p.id)).tasks.at(-1).state==='completed');
 release=null;const competing=await Promise.all([call(`/projects/${p.id}/run`,{prompt:'并发一'}),call(`/projects/${p.id}/run`,{prompt:'并发二'})]);assert.deepEqual(competing.map(x=>x.status).sort(),[200,400]);await competing.find(x=>x.status===200).body.cancel();await waitFor(async()=>release);await call(`/projects/${p.id}/stop`,{});await waitFor(async()=> (await s.get(p.id)).tasks.at(-1).state==='stopped');
 release=null;const second=await call(`/projects/${p.id}/run`,{prompt:'继续'});await second.body.cancel();await waitFor(async()=>release);await call(`/projects/${p.id}/stop`,{});await waitFor(async()=> (await s.get(p.id)).tasks.at(-1).state==='stopped');const stopped=(await s.get(p.id)).tasks.at(-1);assert.equal(stopped.reason,'user-stop');
 mode='instant';const resume=await call(`/projects/${p.id}/run`,{resumeTaskId:stopped.id});await resume.text();assert.equal((await s.get(p.id)).tasks.at(-1).attempts,2);
 assert.equal((await call(`/projects/${p.id}/runtime-error`,{revision:0,message:'旧版错误'})).status,400);assert.equal((await call(`/projects/${p.id}/runtime-error`,{revision:1,message:'提交错误 test-key-only',source:'index.js',line:7,stack:'mock stack'})).status,200);const repair=await call(`/projects/${p.id}/run`,{repair:true});await repair.text();assert.match(observedPrompt,/提交错误/);assert.doesNotMatch(observedPrompt,/test-key-only/);assert.match(observedPrompt,/index.js/);
 mode='wait';release=null;const third=await call(`/projects/${p.id}/run`,{prompt:'重启场景'});await third.body.cancel();await waitFor(async()=>release);await studio.close();assert.equal((await s.get(p.id)).tasks.at(-1).state,'interrupted');
 studio=await startStudio({root:s.root,port:0,production:true,seed:false,build:fakeBuild,agent});headers={'X-Studio-Token':studio.token,'Content-Type':'application/json'};await call('/settings',{baseUrl:'http://localhost',model:'mock',apiKey:'test-key-only'});const interrupted=(await s.get(p.id)).tasks.at(-1);await writeSource(path.join(s.dir(p.id),'revisions','1'),'src/pages/index/index.css','page{color:red}');assert.equal((await call(`/projects/${p.id}/run`,{resumeTaskId:interrupted.id})).status,400);await studio.close();
});
import {spawn} from 'node:child_process';
test('M2 hard process termination is recovered as interrupted by a new Studio instance',async()=>{
 const s=await fresh();const script=`import {Store} from ${JSON.stringify(new URL('../server/store.mjs',import.meta.url).href)};import {createTask} from ${JSON.stringify(new URL('../server/harness.mjs',import.meta.url).href)};const s=new Store(${JSON.stringify(s.root)});await s.init();const p=await s.create('硬中断');await createTask(s,p,'未完成需求');console.log('READY');setInterval(()=>{},1000);`;
 const child=spawn(process.execPath,['--input-type=module','-e',script],{windowsHide:true,stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{let raw='';child.stdout.on('data',c=>{raw+=c;if(raw.includes('READY'))resolve();});child.on('error',reject);child.on('exit',code=>{if(!raw.includes('READY'))reject(new Error('child failed '+code));});});await new Promise(r=>{child.once('exit',r);child.kill('SIGKILL');});const studio=await startStudio({root:s.root,port:0,production:true,seed:false,build:fakeBuild});try{assert.equal((await studio.store.list())[0].tasks[0].state,'interrupted');}finally{await studio.close();}
});
test('M2 checkpoint write failure cannot report completed',async()=>{
 const s=await fresh();const studio=await startStudio({root:s.root,port:0,production:true,seed:false,build:fakeBuild,agent:async({project,emit})=>{emit({type:'status',text:'checkpoint-experiment'});return project;}});try{const headers={'X-Studio-Token':studio.token,'Content-Type':'application/json'};const post=(url,body)=>fetch(studio.url+'/api'+url,{method:'POST',headers,body:JSON.stringify(body)});const p=await(await post('/projects',{title:'checkpoint'})).json();await post('/settings',{baseUrl:'http://localhost',model:'mock',apiKey:'fixture'});const save=studio.store.save.bind(studio.store);let failed=false;studio.store.save=async project=>{if(!failed&&project.tasks.at(-1)?.events.at(-1)?.text==='checkpoint-experiment'){failed=true;throw new Error('expected disk write failure');}return save(project);};const response=await post(`/projects/${p.id}/run`,{prompt:'开始'});const events=await response.text();assert.equal(failed,true);assert.ok(!events.includes('"type":"done"'));assert.equal((await s.get(p.id)).tasks.at(-1).state,'interrupted');}finally{await studio.close();}
});
import {verifyPreview} from '../server/verify.mjs';
test('M3 rejects empty or meaningless business assertions before launching a browser',async()=>{for(const steps of [[{action:'click',selector:'.x'}],[{action:'text',selector:'.x',value:''}],[{action:'text',selector:'.x'}],[{action:'count',selector:'.x',value:-1}],[{action:'count',selector:'.x',value:NaN}]])await assert.rejects(verifyPreview('unused',steps));});
