import {waitProjectReady} from './project-fixture.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import http from 'node:http';
import {Store} from '../server/store.mjs';import {startStudio} from '../server/index.mjs';import {runAgent} from '../server/agent.mjs';import {textRedactor} from '../server/harness.mjs';
const key='fixture-only-boundary-secret-ABCDEF';const build=async d=>{await fs.mkdir(path.join(d,'dist/h5'),{recursive:true});await fs.writeFile(path.join(d,'dist/h5/index.html'),'<html><head></head><body>fixture</body></html>');};
test('all key delta splits and repeated partial prefixes redact without losing ordinary text',()=>{for(let split=1;split<key.length;split++){const r=textRedactor(key);const output=[r.push('开始 '+key.slice(0,split)),r.push(key.slice(split)+' 完毕 '+key),r.flush()].join('');assert.equal(output,'开始 [密钥已隐藏] 完毕 [密钥已隐藏]');}const r=textRedactor('abcab');assert.equal([r.push('abc'),r.push('abcab!'),r.flush()].join(''),'[密钥已隐藏]cab!');const partial=textRedactor(key);assert.equal(partial.push(key.slice(0,-1))+partial.flush(),'[密钥已隐藏]');});
for(const stop of [false,true])test(stop?'accepted stop at commit entry never publishes or completes':'split SSE and nested verification results never persist or stream key',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'sprout-security-'));const scripts=[{name:'write_file',args:{path:'src/pages/index/index.css',content:'page{color:green}'}},{name:'build_preview',args:{}},{name:'verify_preview',args:{steps:[{action:'text',selector:'body',value:key}]}}];let n=0;const model=http.createServer(async(req,res)=>{for await(const c of req){}const action=scripts[n++];res.writeHead(200,{'Content-Type':'text/event-stream'});const send=(delta,finish_reason=null)=>res.write('data: '+JSON.stringify({id:'fixture',choices:[{index:0,delta,finish_reason}]})+'\n\n');send({role:'assistant'});if(action){send({tool_calls:[{index:0,id:'call-'+n,type:'function',function:{name:action.name,arguments:JSON.stringify(action.args)}}]});send({},'tool_calls');}else{send({content:'完成 '+key.slice(0,17)});await new Promise(r=>setTimeout(r,10));send({content:key.slice(17)});send({},'stop');}res.end('data: [DONE]\n\n');});await new Promise(r=>model.listen(0,'127.0.0.1',r));
 const studio=await startStudio({root,port:0,production:true,seed:false,build,agent:args=>runAgent({...args,verify:async(_d,steps)=>({state:'passed',steps,storage:{[key]:key,nested:[{text:key}],fixture:key},kind:'stub-verifier'})})});let release;
 try{const headers={'X-Studio-Token':studio.token,'Content-Type':'application/json'};const post=(url,body)=>fetch(studio.url+'/api'+url,{method:'POST',headers,body:JSON.stringify(body)});const p=await(await post('/projects',{title:'安全边界'})).json();await waitProjectReady(studio,p);const prior=await studio.store.get(p.id);prior.verification={state:'passed',revision:p.revision,steps:[{action:'text',selector:'body',value:'baseline'}]};await studio.store.save(prior);await post('/settings',{provider:'custom',baseUrl:`http://127.0.0.1:${model.address().port}/v1`,model:'mock',apiKey:key});let entered;const gate=new Promise(r=>entered=r),released=new Promise(r=>release=r);const commit=studio.store.commit.bind(studio.store);if(stop)studio.store.commit=async(...args)=>{entered();await released;return commit(...args);};const response=await post(`/projects/${p.id}/run`,{prompt:'修改并检查'}),rawPromise=response.text();if(stop){await gate;assert.equal((await post(`/projects/${p.id}/stop`,{})).status,200);release();}const raw=await rawPromise,events=raw.trim().split('\n').map(JSON.parse),joined=events.filter(e=>e.type==='text').map(e=>e.text).join('');assert.ok(!joined.includes(key));assert.ok(!raw.includes(key));const persisted=await studio.store.get(p.id);assert.ok(!(await fs.readFile(path.join(studio.store.dir(p.id),'project.json'),'utf8')).includes(key));for(const f of await fs.readdir(path.join(studio.store.dir(p.id),'sessions')))assert.ok(!(await fs.readFile(path.join(studio.store.dir(p.id),'sessions',f),'utf8')).includes(key));if(stop){assert.equal(persisted.revision,p.revision);assert.equal(persisted.tasks.at(-1).state,'stopped');assert.deepEqual(persisted.verification,prior.verification);assert.ok(!persisted.messages.some(m=>m.role==='assistant'&&m.text==='完成 [密钥已隐藏]'));assert.ok(!events.some(e=>e.type==='done'));}else{assert.equal(persisted.revision,p.revision+1);assert.equal(persisted.verification.steps[0].value,'[密钥已隐藏]');assert.equal(persisted.verification.storage.fixture,'[密钥已隐藏]');assert.equal(persisted.versions.at(-1).verification.storage.nested[0].text,'[密钥已隐藏]');}}
 finally{release?.();await studio.close();model.closeAllConnections();await new Promise(r=>model.close(r));}
});
test('stop after publication boundary is rejected explicitly, and completed publication is coherent',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'sprout-publication-'));let entered,release;const gate=new Promise(r=>entered=r),released=new Promise(r=>release=r);const studio=await startStudio({root,port:0,production:true,seed:false,build,agent:async({store,project,signal,onPublish})=>{const d=await store.draft(project.id);await build(d);return store.commit(project,d,'边界',{signal,beforePublish:onPublish});}});try{const headers={'X-Studio-Token':studio.token,'Content-Type':'application/json'},post=(url,body)=>fetch(studio.url+'/api'+url,{method:'POST',headers,body:JSON.stringify(body)});const p=await(await post('/projects',{title:'发布边界'})).json();await waitProjectReady(studio,p);await post('/settings',{baseUrl:'http://localhost',model:'mock',apiKey:'fixture'});const save=studio.store.save.bind(studio.store);studio.store.save=async p=>{if(p.revision===2){entered();await released;}return save(p);};const response=await post(`/projects/${p.id}/run`,{prompt:'保存版本'}),rawPromise=response.text();await gate;const stopped=await post(`/projects/${p.id}/stop`,{});assert.equal(stopped.status,409);assert.match((await stopped.json()).error,/无法停止/);release();const events=await rawPromise;assert.match(events,/"type":"done"/);assert.equal((await studio.store.get(p.id)).revision,2);}finally{release();await studio.close();}
});
import {verifyPreview} from '../server/verify.mjs';
test('delayed real-browser count waits for business update, rather than suggesting repair',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'sprout-count-'));await fs.mkdir(path.join(root,'dist/h5'),{recursive:true});await fs.writeFile(path.join(root,'dist/h5/index.html'),'<html><head></head><body><button onclick="setTimeout(()=>{const e=document.createElement(\'div\');e.className=\'item\';e.textContent=\'新增成功\';document.body.append(e)},200)">新增</button></body></html>');const result=await verifyPreview(root,[{action:'click',selector:'button'},{action:'count',selector:'.item',value:1}]);assert.equal(result.state,'passed',JSON.stringify(result));});
