import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {verifyPreview,validateVerificationPlan,validateVerificationEvidence} from '../server/verify.mjs';
const short='独立验收一二三',long='天地玄黄宇宙洪荒日月盈昃辰宿列张'.repeat(8).slice(0,120);
const steps=[{action:'fill',selector:'#input',value:short},{action:'click',selector:'#generate'},{action:'qr',selector:'#qr',value:short},{action:'fill',selector:'#input',value:long},{action:'click',selector:'#generate'},{action:'qr',selector:'#qr',value:long},{action:'fill',selector:'#input',value:''},{action:'click',selector:'#generate'},{action:'text',selector:'#message',value:'请输入内容'}];
test('QR empty feedback must appear/change from this submission; constant/hidden labels cannot pass',async()=>{
 const modules={};for(const name of await fs.readdir('templates/mini/src/vendor/qr/core'))if(name.endsWith('.js'))modules['./'+name.slice(0,-3)]=await fs.readFile('templates/mini/src/vendor/qr/core/'+name,'utf8');const moduleCode=Object.entries(modules).map(([name,src])=>JSON.stringify(name)+':function(require,module,exports){'+src+'}').join(',');
 const report={cases:[]},root=await fs.mkdtemp(path.join(os.tmpdir(),'sprout-empty-feedback-'));await fs.mkdir(path.join(root,'dist/h5'),{recursive:true});
 try{for(const mode of ['normal-retains-qr','normal-please-first','constant-empty-label','hidden-empty-label','invisible-new-feedback','count-removes-qr']){
  const feedback=mode==='normal-please-first'?'请先输入要生成二维码的文字':'请输入内容';
  const constant=mode==='constant-empty-label'||mode==='hidden-empty-label';
  const html=`<html><head></head><body style="margin:8px"><input id="input"><button id="generate">生成</button><div id="message" ${mode==='hidden-empty-label'?'hidden':mode==='invisible-new-feedback'?'style="opacity:0"':''}>${constant?'请输入内容':''}</div><div id="output"></div><script>const modules={${moduleCode}},cache={};function require(id){if(cache[id])return cache[id].exports;const m={exports:{}};cache[id]=m;modules[id](require,m,m.exports);return m.exports}const QR=require('./index');document.querySelector('#generate').onclick=()=>{const t=document.querySelector('#input').value;if(!t){${constant?'return;':mode==='count-removes-qr'?"document.querySelector('#output').innerHTML='';return;":"document.querySelector('#message').textContent="+JSON.stringify(feedback)+";return;"}}${constant?'':"document.querySelector('#message').textContent='';"}const q=new QR(-1,0);q.addData(encodeURIComponent(t).replace(/%([0-9a-f]{2})/gi,(_,h)=>String.fromCharCode(parseInt(h,16))));q.make();const n=q.getModuleCount(),s=(n+8)*3,c=document.createElement('canvas');c.id='qr';c.width=c.height=s;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,s,s);ctx.fillStyle='black';for(let y=0;y<n;y++)for(let x=0;x<n;x++)if(q.isDark(y,x))ctx.fillRect((x+4)*3,(y+4)*3,3,3);document.querySelector('#output').replaceChildren(c);};</script></body></html>`;
  await fs.writeFile(path.join(root,'dist/h5/index.html'),html);const plan=mode==='count-removes-qr'?steps.map((s,i)=>i===8?{action:'count',selector:'#qr',value:0}:s):steps.map((s,i)=>i===8?{...s,value:feedback}:s);validateVerificationPlan(plan,{profile:'text-qr'});const result=await verifyPreview(root,plan);validateVerificationEvidence(result,plan,{profile:'text-qr'});report.cases.push({mode,result});
  if(constant||mode==='invisible-new-feedback'){assert.equal(result.state,'failed',JSON.stringify(result));if(mode==='constant-empty-label')assert.match(result.error,/常驻提示/);assert.equal(result.qrChecks.length,2);}else{assert.equal(result.state,'passed',JSON.stringify(result));assert.equal(result.emptyChecks.length,1);assert.equal(result.emptyChecks[0].transition,true);assert.equal(result.emptyChecks[0].fillStep,7);assert.equal(result.emptyChecks[0].clickStep,8);assert.equal(result.emptyChecks[0].step,9);assert.throws(()=>validateVerificationEvidence({...result,emptyChecks:[]},plan,{profile:'text-qr'}),/空输入检查缺少/);}
 }}finally{await fs.rm(root,{recursive:true,force:true});}
 await fs.mkdir('test-results',{recursive:true});await fs.writeFile('test-results/studio-repair-empty-feedback.json',JSON.stringify(report,null,2));
});
