import fs from 'node:fs/promises';
import path from 'node:path';
import { createHash,randomUUID } from 'node:crypto';
import { atomicJson,readSources } from './store.mjs';
export const LIMITS={attempts:3,tools:40,builds:3,milliseconds:600000,memoryChars:48000};
export function checkpointBudget(task,now=Date.now()){if(task.budgetCheckpointAt)task.budgetUsedMs=Math.min(LIMITS.milliseconds,(task.budgetUsedMs||0)+Math.max(0,now-task.budgetCheckpointAt));task.budgetCheckpointAt=now;}
export function exhaustedBudget(task={}){return (task.toolCalls||0)>=LIMITS.tools||(task.buildAttempts||0)>=LIMITS.builds||(task.verifyAttempts||0)>=3||(task.repairPrompts||0)>=3||(task.budgetUsedMs||0)>=LIMITS.milliseconds;}
export function safeText(value,key=''){let text=String(value||'');if(key)text=text.split(key).join('[密钥已隐藏]');return text.replace(/\b(?:sk-[A-Za-z0-9_-]{8,}|Bearer\s+\S+)/gi,'[密钥已隐藏]');}
export function safeValue(value,key=''){return typeof value==='string'?safeText(value,key):Array.isArray(value)?value.map(x=>safeValue(x,key)):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([name,item])=>[safeText(name,key),safeValue(item,key)])):value;}
// Retain only a possible secret prefix; no partial delta can complete a leaked key.
export function textRedactor(key=''){let pending='';return {push(chunk){pending=safeText(pending+String(chunk||''),key);let keep=0;for(let n=1;n<key.length;n++)if(pending.endsWith(key.slice(0,n)))keep=n;const text=pending.slice(0,pending.length-keep);pending=pending.slice(pending.length-keep);return text;},flush(){const text=pending&&key.startsWith(pending)?'[密钥已隐藏]':safeText(pending,key);pending='';return text;}};}
export function normalizeProject(p){p.memory??={goal:p.title,constraints:'',changes:(p.messages||[]).filter(m=>m.role==='user').map(m=>({text:safeText(m.text),time:m.time})),updatedAt:Date.now()};p.tasks??=[];p.runtimeErrors??=[];return p;}
export function remember(p,prompt,key){normalizeProject(p);const text=safeText(prompt,key);if(JSON.stringify(p.memory).length+text.length>LIMITS.memoryChars)throw new Error('需求记录已满，请先在项目需求中整理后继续。');p.memory.changes.push({text,time:Date.now()});p.memory.updatedAt=Date.now();}
export function memoryContext(p){normalizeProject(p);if(JSON.stringify(p.memory).length>LIMITS.memoryChars)throw new Error('历史需求超过上下文容量，请在项目需求中整理；原始对话与记录仍保留。');return JSON.stringify(p.memory);}
export function digestSources(sources){return createHash('sha256').update(JSON.stringify(Object.entries(sources).sort(([a],[b])=>a.localeCompare(b)))).digest('hex');}
export async function sourceDigest(store,p){const dir=p.ready?path.join(store.dir(p.id),'revisions',String(p.revision)):path.join(store.dir(p.id),'current');return digestSources(await readSources(dir));}
export async function createTask(store,p,prompt,previous){normalizeProject(p);if(previous&&(previous.attempts>=LIMITS.attempts||previous.resumable===false||exhaustedBudget(previous)))throw new Error('本任务预算或继续次数已达上限，不能重置预算继续；请核对原结果，整理需求后显式提交新需求。');const task={id:randomUUID(),prompt,state:'running',phase:'理解需求',attempts:(previous?.attempts||0)+1,resumedFrom:previous?.id,baseRevision:p.revision,sourceDigest:await sourceDigest(store,p),startedAt:Date.now(),updatedAt:Date.now(),budgetCheckpointAt:Date.now(),events:[],limits:LIMITS};for(const field of ['toolCalls','buildAttempts','verifyAttempts','repairPrompts','budgetUsedMs'])task[field]=previous?.[field]||0;p.tasks.push(task);p.tasks=p.tasks.slice(-50);await store.save(p);return task;}
export async function recoverTasks(store){for(const item of await store.list()){const p=await store.get(item.id);let changed=false;for(const t of p.tasks){if(t.state==='running'){checkpointBudget(t);t.state='interrupted';t.resumable=!exhaustedBudget(t);if(!t.resumable)t.reason='recovery-budget-exhausted';t.phase=t.resumable?'服务重启，任务中断；可核对源码后继续':'任务中断且预算已耗尽；请核对结果后显式提交新需求';t.updatedAt=Date.now();changed=true;}}if(changed)await store.save(p);}}
