import express from 'express';
import path from 'node:path';
import fs from 'node:fs/promises';
import {storageBridge} from './preview-bridge.mjs';
import { chromium } from 'playwright-core';
export async function verifyPreview(dir,steps,{signal,initialStorage={}}={}){
 if(!Array.isArray(steps)||!steps.length||steps.length>20)throw new Error('功能检查需要 1–20 个步骤。');
 for(const s of steps){if(!['click','fill','text','count','reload'].includes(s.action)||(s.action!=='reload'&&(typeof s.selector!=='string'||s.selector.length>300))||String(s.value??'').length>2000)throw new Error('功能检查步骤格式无效。');}
 if(!steps.some(s=>['text','count'].includes(s.action)))throw new Error('至少需要一个业务文本或数量断言。');for(const s of steps){if(['fill','text'].includes(s.action)&&typeof s.value!=='string')throw new Error('填写与文本断言需要文字值。');if(s.action==='text'&&!s.value.trim())throw new Error('文本断言不能为空。');if(s.action==='count'&&(!Number.isInteger(s.value)||s.value<0))throw new Error('数量断言需要非负整数。');}
 signal?.throwIfAborted();let storage={...initialStorage};const app=express();app.use((req,res,next)=>{res.setHeader('Content-Security-Policy',"default-src 'none'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'none'; media-src 'self'; base-uri 'none'; form-action 'none'");next();});app.get('/',async(req,res)=>{const html=await fs.readFile(path.join(dir,'dist/h5/index.html'),'utf8');res.type('html').send(html.replace('<head>','<head>'+storageBridge('verification',storage,0)));});app.use(express.static(path.join(dir,'dist/h5')));const server=await new Promise(r=>{const s=app.listen(0,'127.0.0.1',()=>r(s));});let browser;const errors=[];let index=-1;
 try{browser=await chromium.launch({channel:'msedge',headless:true});const abort=()=>browser.close().catch(()=>{});signal?.addEventListener('abort',abort,{once:true});try{const page=await browser.newPage();await page.exposeFunction('__sproutStorage',values=>{storage=values;});await page.addInitScript(()=>window.addEventListener('message',event=>{if(event.data?.type==='sprout-storage')window.__sproutStorage(event.data.values);}));page.setDefaultTimeout(4000);page.on('pageerror',e=>errors.push(e.stack||e.message));await page.goto(`http://127.0.0.1:${server.address().port}`,{timeout:15000});for(const [i,s] of steps.entries()){index=i;signal?.throwIfAborted();if(s.action==='reload'){await page.waitForTimeout(100);await page.reload();continue;}const loc=page.locator(s.selector);if(s.action==='click')await loc.click();if(s.action==='fill')await loc.fill(String(s.value));if(s.action==='text'){let actual='';for(let poll=0;poll<80;poll++){actual=await loc.innerText();if(actual.includes(String(s.value)))break;await page.waitForTimeout(50);}if(!actual.includes(String(s.value)))throw new Error(`步骤 ${i+1} 文本不符：实际 ${actual.slice(0,500)}；期待 ${s.value}`);}if(s.action==='count'){const actual=await loc.count();if(actual!==Number(s.value))throw new Error(`数量不符：实际 ${actual}；期待 ${s.value}`);}}await page.waitForTimeout(100);if(errors.length)throw new Error(errors.join('\n').slice(0,3000));return {state:'passed',steps,time:Date.now(),kind:'real-browser',storage};}finally{signal?.removeEventListener('abort',abort);}}
 catch(e){return {state:'failed',steps,step:index+1,error:e.message.slice(0,3000),runtimeErrors:errors,time:Date.now(),kind:'real-browser',storage};}
 finally{await browser?.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
}
