import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Sprout,Plus,Settings2,ArrowUp,ArrowUpRight,ChevronDown,ChevronRight,Check,CheckCheck,Code2,Download,FolderOpen,History,LayoutGrid,Loader2,MessageSquare,MoreHorizontal,PanelLeftClose,Play,RefreshCw,ShieldCheck,Smartphone,Sparkles,Square,Terminal,Wifi,X,Leaf,Copy,ArrowLeft,BookOpen,Undo2} from 'lucide-react';
import './style.css';
import {createStudioClient} from '../server/studio-client.mjs';

const token=document.querySelector('meta[name="studio-token"]')?.content||'';
const studioClient=createStudioClient({token});
const api=studioClient.json;
const json=value=>JSON.stringify(value);
const deepseekModels=[{id:'deepseek-flash',name:'DeepSeek Flash'},{id:'deepseek-v4-pro',name:'DeepSeek V4 Pro'}];
function App(){
  const [switchingModel,setSwitchingModel]=useState(false);
  const [projects,setProjects]=useState([]),[active,setActive]=useState(null),[settings,setSettings]=useState(null),[previewOrigin,setPreviewOrigin]=useState('');
  const [modal,setModal]=useState(null),[prompt,setPrompt]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[stream,setStream]=useState(''),[error,setError]=useState(''),[toast,setToast]=useState('');
  const [tab,setTab]=useState('preview'),[width,setWidth]=useState(375),[refresh,setRefresh]=useState(0),[code,setCode]=useState({}),[file,setFile]=useState('src/pages/index/index.jsx'),[logs,setLogs]=useState([]),[collapsed,setCollapsed]=useState(false);
  const bottom=useRef(null),input=useRef(null),abortRef=useRef(null),sendingRef=useRef(false);
  function notify(text){setToast(text);setTimeout(()=>setToast(''),3500);}
  async function switchModel(model){
    if(busy||switchingModel)return;
    setSwitchingModel(true);
    try{const saved=await api('/settings',{method:'POST',body:json({provider:settings.provider,baseUrl:settings.baseUrl,model})});setSettings(saved);notify('已切换至 '+model);}catch(e){notify(e.message);}finally{setSwitchingModel(false);}
  }
  async function boot(){try{const data=await api('/bootstrap');setProjects(data.projects);setSettings(data.settings);setPreviewOrigin(data.previewOrigin);setActive(data.projects[0]||null);if(data.initialError||data.settings.keyStorage?.warning)setError(data.initialError||data.settings.keyStorage.warning);}catch(e){setError(e.message);}}
  useEffect(()=>{boot();},[]);
  useEffect(()=>{if(active?.id&&!modal)input.current?.focus();},[active?.id,modal]);
  useEffect(()=>{let cancelled=false;const refreshSettings=()=>studioClient.publicSettings().then(value=>{if(!cancelled)setSettings(value);}).catch(()=>{});window.addEventListener('focus',refreshSettings);const timer=setInterval(refreshSettings,1500);return()=>{cancelled=true;clearInterval(timer);window.removeEventListener('focus',refreshSettings);};},[]);
  useEffect(()=>{
    function receive(event){const frame=document.querySelector('iframe[title="小程序交互预览"]');if(event.origin!==previewOrigin||event.source!==frame?.contentWindow||event.data?.projectId!==active?.id)return;
      if(event.data.type==='sprout-storage')api(`/projects/${active.id}/storage`,{method:'POST',body:json({values:event.data.values})}).catch(e=>setError('预览数据保存失败：'+e.message));
      if(event.data.type==='sprout-runtime-error'){setError('预览运行错误：'+String(event.data.message).slice(0,2000));api(`/projects/${active.id}/runtime-error`,{method:'POST',body:json(event.data)}).then(updateProject).catch(e=>setError(e.message));}
    }
    window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);
  },[active?.id,previewOrigin]);
  useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'});},[active?.messages,stream,status]);
  useEffect(()=>{if(active&&tab==='code')api(`/projects/${active.id}/files`).then(setCode).catch(e=>notify(e.message));},[active?.id,active?.revision,tab]);
  function updateProject(p){setActive(p);setProjects(old=>[p,...old.filter(x=>x.id!==p.id)]);}
  async function selectProject(p){if(busy)return;setActive(p);setError('');setStream('');setLogs([]);setTab('preview');}
  const running=active?.tasks?.some(t=>t.state==='running');
  useEffect(()=>{if(!active?.id)return;let cancelled=false;const timer=setInterval(()=>{api(`/projects/${active.id}`).then(p=>{if(!cancelled&&(p.tasks?.some(t=>t.state==='running')||running||p.revision!==active.revision||JSON.stringify(p.initialization)!==JSON.stringify(active.initialization))){updateProject(p);setStatus(p.tasks.at(-1)?.phase||'');}}).catch(()=>{});},1000);return()=>{cancelled=true;clearInterval(timer);};},[active?.id,running,active?.revision,active?.initialization?.state]);
  async function send(options={}){
    if((!prompt.trim()&&!options.resumeTaskId&&!options.repair)||busy||running||switchingModel||!active||sendingRef.current)return;
    sendingRef.current=true;
    let currentSettings;try{currentSettings=await studioClient.publicSettings();setSettings(currentSettings);}catch(e){sendingRef.current=false;setError(e.message);return;}
    if(!currentSettings.hasKey){sendingRef.current=false;setModal('settings');return;}
    const message=prompt.trim();setPrompt('');setError('');setBusy(true);setStream('');setLogs([]);setStatus('正在理解你的想法…');
    setActive(p=>({...p,messages:[...p.messages,{role:'user',text:message,time:Date.now()}]}));
    try{
      const controller=new AbortController();abortRef.current=controller;
      for await(const event of studioClient.run(active.id,{prompt:message,...options},{signal:controller.signal})){
          if(event.type==='status'){setStatus(event.text);setLogs(old=>[...old,event.text]);}
          if(event.type==='text')setStream(old=>old+event.text);
          if(event.type==='done'){updateProject(event.project);setStream('');notify(event.project.revision>active.revision?'新版本已保存，预览已更新':'小芽已回复');}
          if(event.type==='error'){setError(event.text);if(event.project)updateProject(event.project);}
      }
    }catch(e){setError(e.name==='AbortError'?'连接中断，任务仍可能在制作，请查看进度。':e.message);}
    finally{sendingRef.current=false;setBusy(false);setStatus('');setStream('');abortRef.current=null;try{const p=await api(`/projects/${active.id}`);updateProject(p);}catch{}}
  }
  async function stop(){try{await api(`/projects/${active.id}/stop`,{method:'POST'});setStatus('正在停止…');}catch(e){notify(e.message);}}
  async function exportProject(){try{const res=await studioClient.export(active.id);const url=URL.createObjectURL(await res.blob());const a=document.createElement('a');a.href=url;a.download=`${active.title}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);notify('已导出源码与微信小程序产物');}catch(e){notify(e.message);}}
  function suggestion(text){setPrompt(text);input.current?.focus();}
  return <div className={'studio '+(collapsed?'sidebar-collapsed':'')}>
    <aside className="sidebar">
      <div className="brand"><div className="brand-icon"><Sprout size={25}/></div><div><strong>小芽<span> Studio</span></strong><small>让想法，生长成应用</small></div><button className="icon-button collapse-button" title="收起侧栏" onClick={()=>setCollapsed(true)}><PanelLeftClose size={17}/></button></div>
      <button className="new-project" onClick={()=>setModal('new')} disabled={busy}><Plus size={18}/> 新建小程序 <span>＋</span></button>
      <div className="sidebar-heading">工作空间 <span>本地</span></div>
      <button className="nav-item selected"><LayoutGrid size={17}/>我的小程序 <span>{projects.length}</span></button>
      <div className="sidebar-heading project-heading">最近项目 <FolderOpen size={13}/></div>
      <div className="project-list">{projects.map(p=><button key={p.id} disabled={busy} className={'project-item '+(active?.id===p.id?'active':'')} onClick={()=>selectProject(p)}><div className="project-mini-icon"><Leaf size={16}/></div><div><strong>{p.title}</strong><small>{p.sample?'示例项目':`${p.versions.length} 个版本`} · {new Date(p.updatedAt).toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})}</small></div>{active?.id===p.id&&<span className="active-dot"/>}</button>)}</div>
      <div className="sidebar-bottom"><div className="local-card"><ShieldCheck size={17}/><div><strong>你的创意，留在本地</strong><p>项目保存在这台电脑上<br/>调用模型时发送对话与代码</p></div></div><button className="settings-link" onClick={()=>setModal('settings')} disabled={busy}><Settings2 size={17}/>模型与设置<span className={'connection-dot '+(settings?.hasKey?'connected':'')}/></button><div className="sidebar-footer"><span>SPROUT STUDIO</span><span>v0.1 DEMO</span></div></div>
    </aside>
    <main>
      <header className="topbar"><div className="breadcrumb">{collapsed&&<button title="展开侧栏" className="icon-button" onClick={()=>setCollapsed(false)}><LayoutGrid size={18}/></button>}<span>我的小程序</span><ChevronRight size={14}/><strong>{active?.title||'正在打开工作空间'}</strong>{active?.sample&&<span className="sample-tag">示例</span>}</div><div className="top-actions"><span className="saved-state"><span className="connection-dot connected"/>{busy?'制作中':'已保存到本地'}</span><button className="plain-button" disabled={!active||busy} onClick={()=>setModal('history')}><History size={15}/>版本记录</button><button className="plain-button" disabled={!active||busy||running} onClick={()=>setModal('memory')}>项目需求</button><button className="plain-button" disabled={!active} onClick={()=>setModal('verification')}>功能检查</button><button className="export-button" disabled={!active?.ready||busy} onClick={exportProject}><Download size={15}/>导出小程序</button></div></header>
      <div className="workbench">
        <section className="chat-panel"><div className="panel-heading"><div><MessageSquare size={16}/><strong>和小芽一起创造</strong></div><span className="agent-label"><span/>PI Agent</span></div>
          <div className="chat-scroll"><div className="intro"><div className="intro-symbol"><Sprout size={27}/></div><div className="intro-kicker">FROM AN IDEA TO SOMETHING REAL</div><h1>让你的想法，<br/>长出自己的样子<span>。</span></h1><p>说说你想做什么，剩下的我们一起完成。</p></div>
            {active?.messages.map((m,i)=><div className={'message '+m.role} key={i}>{m.role==='assistant'&&<div className="avatar"><Sprout size={16}/></div>}<div className="message-content">{m.role==='assistant'&&<div className="message-name">小芽 <span>{i===0?'你的应用搭建伙伴':'PI Agent'}</span></div>}<div className="message-text">{m.text}</div>{i===0&&active.sample&&<div className="completed-card"><div className="completed-title"><div className="tiny-app-icon"><Leaf size={19}/></div><div><strong>日常 · 习惯打卡</strong><small>一个温柔的日常习惯小程序</small></div><Check size={16}/></div><div className="completed-features"><span><CheckCheck size={12}/>新增与打卡</span><span><CheckCheck size={12}/>本地保存</span><span><CheckCheck size={12}/>七天统计</span></div><div className="completed-footer"><span className="connection-dot connected"/>内置示例 · 非 AI 生成<span>在右侧试一试 <ArrowUpRight size={13}/></span></div></div>}</div></div>)}
            {active?.messages.length===1&&<div className="ideas"><div className="ideas-label"><Sparkles size={13}/>接下来，试着告诉我</div>{(active.sample?['换成暖橙色，风格更活泼一些','增加删除习惯的功能','改成一个记录读书进度的小程序']:['做一个输入文字就能生成二维码的小程序','做一个记录读书进度的小程序','做一个旅行行李清单']).map((s,i)=><button disabled={busy} onClick={()=>suggestion(s)} key={s}><span className="idea-number">0{i+1}</span>{s}<ArrowUpRight size={14}/></button>)}</div>}
            {(busy||running)&&<div className="message assistant"><div className="avatar"><Sprout size={16}/></div><div className="message-content"><div className="message-name">小芽<span>正在制作</span></div>{stream&&<div className="message-text streaming">{stream}</div>}<div className="progress-line"><Loader2 className="spin" size={14}/>{status}</div></div></div>}
            {error&&<div className="error-card"><strong>这一步还没有完成</strong><p>{error.slice(0,900)}</p><button onClick={()=>{navigator.clipboard?.writeText(error);notify('错误详情已复制');}}><Copy size={12}/>复制详情</button></div>}<div ref={bottom}/>
          </div>
          <div className="composer-area">{active?.tasks?.at(-1)&&<div className="security-note"><span>{active.tasks.at(-1).phase}</span>{['interrupted','failed','stopped'].includes(active.tasks.at(-1).state)&&active.tasks.at(-1).resumable!==false&&<button disabled={busy||running} onClick={()=>send({resumeTaskId:active.tasks.at(-1).id})}>核对源码并继续</button>}{running&&!busy&&<button onClick={stop}>停止制作</button>}</div>}{active?.runtimeErrors?.at(-1)?.revision===active?.revision&&<button disabled={busy||running} onClick={()=>send({repair:true})}>修复当前运行错误</button>}{!settings?.hasKey&&<button className="connect-notice" onClick={()=>setModal('settings')}><span><Wifi size={13}/>连接 DeepSeek，让想法开始生长</span><ArrowUpRight size={14}/></button>}<div className={'composer '+(busy?'is-busy':'')}><textarea ref={input} value={prompt} disabled={busy||running||!active} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send();}}} placeholder="描述你的小程序，或说说想修改什么…" rows={3}/><div className="composer-toolbar"><button className="model-picker" onClick={()=>setModal('settings')} disabled={busy}><span className="deepseek-mark">≈</span>{settings?.provider==='custom'?'自定义模型':'DeepSeek'}<ChevronDown size={12}/></button>{settings?.provider==='deepseek'&&<select className="quick-model" aria-label="切换 DeepSeek 模型" value={settings.model} disabled={busy||switchingModel} onChange={e=>switchModel(e.target.value)}>{!deepseekModels.some(m=>m.id===settings.model)&&<option value={settings.model}>{settings.model}</option>}{deepseekModels.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select>}<span className="composer-spacer"/><span className="shortcut">Enter 发送</span>{busy?<button className="send-button" onClick={stop} title="停止制作"><Square size={15}/></button>:<button className="send-button" onClick={()=>send()} disabled={!prompt.trim()||!active||switchingModel} title="发送消息"><ArrowUp size={19}/></button>}</div></div><div className="composer-footnote"><ShieldCheck size={11}/>密钥仅用于模型请求，不会写入小程序代码</div></div>
        </section>
        <section className="preview-panel"><div className="preview-toolbar"><div className="segmented">{[['preview',Smartphone,'预览'],['code',Code2,'代码']].map(([key,Icon,label])=><button className={tab===key?'active':''} onClick={()=>setTab(key)} key={key}><Icon size={14}/>{label}</button>)}</div><div className="preview-tools"><span className="preview-kind">{tab==='preview'?'H5 交互预览':'Taro 源码'}</span><button title="刷新预览" className="icon-button" onClick={()=>setRefresh(x=>x+1)} disabled={!active?.ready}><RefreshCw size={15}/></button><button title="构建日志" className={'icon-button '+(tab==='logs'?'active':'')} onClick={()=>setTab(tab==='logs'?'preview':'logs')}><Terminal size={15}/></button></div></div>
          {tab==='preview'?<div className="preview-canvas"><div className="device-selector"><Smartphone size={13}/><select aria-label="预览尺寸" value={width} onChange={e=>setWidth(Number(e.target.value))}><option value={375}>标准手机 · 375 × 720</option><option value={320}>小屏手机 · 320 × 720</option><option value={414}>大屏手机 · 414 × 720</option></select><ChevronDown size={12}/></div><PhonePreview active={active} width={width} refresh={refresh} previewOrigin={previewOrigin}/><div className="preview-caption"><span className="connection-dot connected"/>{active?.ready?'可点击、输入和交互':'预览准备期间可开始对话'}<span className="caption-divider">·</span>数据仅保存在本机</div><div className="preview-disclaimer">网页预览效果 · 微信专属能力需在开发者工具中验证</div></div>:tab==='code'?<div className="code-panel"><div className="file-tabs">{Object.keys(code).map(name=><button className={name===file?'active':''} key={name} onClick={()=>setFile(name)}>{name.split('/').pop()}</button>)}</div><div className="code-file-path"><Code2 size={13}/>{file}<button className="icon-button" title="复制代码" onClick={()=>{navigator.clipboard?.writeText(code[file]||'');notify('代码已复制');}}><Copy size={13}/></button></div><pre>{(code[file]||'').split('\n').map((line,i)=><div className="code-line" key={i}><span>{i+1}</span><code>{line||' '}</code></div>)}</pre></div>:<div className="logs-panel"><Terminal size={22}/><h3>制作记录</h3><p>这里会显示本次制作的工具调用和编译进度。</p>{logs.length?logs.map((line,i)=><div className="log-line" key={i}><Check size={13}/>{line}</div>):<div className="log-empty">暂时没有运行记录。连接模型后开始制作。</div>}</div>}
          <div className="preview-bottom"><span><span className="connection-dot connected"/>{active?.ready?'预览已就绪':active?.initialization?.state==='failed'?'预览准备失败':active?.initialization?.state==='interrupted'?'预览准备已中断':'正在后台准备'}</span><span>React + Taro <span className="caption-divider">/</span>版本 {String(active?.revision||1).padStart(2,'0')}</span></div>
        </section>
      </div>
    </main>
    {modal==='verification'&&active&&<Modal title="功能检查" subtitle="查看本次实际检查的范围。编译通过不代表所有业务功能通过。" onClose={()=>setModal(null)}><p>{active.verification?.state==='passed'?'所列检查通过':active.verification?.state==='failed'?'检查失败':'实际功能待验证'} · 版本 {active.verification?.revision||active.revision}</p>{active.verification?.steps?.map((s,i)=><p key={i}>{i+1}. {({click:'点击',fill:'填写',text:'文本包含',count:'数量等于',reload:'刷新'})[s.action]} {s.selector} {s.value??''}</p>)}{active.verification?.reason&&<p>{active.verification.reason}</p>}</Modal>}
    {modal==='memory'&&active&&<MemoryModal project={active} onClose={()=>setModal(null)} onSaved={p=>{updateProject(p);setModal(null);notify('项目需求已修正');}}/>}
    {modal==='settings'&&<SettingsModal current={settings} onClose={()=>setModal(null)} onSaved={s=>{setSettings(s);setModal(null);notify(s.keyStorage?.mode==='memory'?'设置已保存，密钥仅用于本次启动':'模型设置已安全保存');}}/>}
    {modal==='new'&&<NewProjectModal onClose={()=>setModal(null)} onCreated={p=>{updateProject(p);setModal(null);setTab('preview');setError('');setLogs([]);setPrompt('');}}/>}
    {modal==='history'&&active&&<HistoryModal project={active} onClose={()=>setModal(null)} onRestore={p=>{updateProject(p);setModal(null);notify('已恢复，并保存为新版本');}}/>}
    {toast&&<div className="toast"><Check size={16}/>{toast}</div>}
  </div>;
}

function PhonePreview({active,width,refresh,previewOrigin}){
  const stage=useRef(null),[scale,setScale]=useState(1);
  useEffect(()=>{const element=stage.current;if(!element)return;const resize=()=>setScale(Math.max(.01,Math.min(1,element.clientWidth/(width+14),element.clientHeight/784)));const observer=new ResizeObserver(resize);observer.observe(element);resize();return()=>observer.disconnect();},[width]);
  const interrupted=active?.initialization?.state==='interrupted',failed=active?.initialization?.state==='failed';
  return <div className="phone-stage" ref={stage}><div className="phone-wrap" style={{width:(width+14)*scale,height:784*scale}}><div className="phone" style={{width:width+14,transform:`scale(${scale})`}}><div className="phone-status"><strong>9:41</strong><div className="phone-island"/><div className="phone-signals"><span>▮▮▮</span><Wifi size={13}/><div className="battery"/></div></div>{active?.ready?<iframe key={`${active.id}-${active.revision}-${refresh}`} title="小程序交互预览" style={{width,height:720}} src={`${previewOrigin}/p/${active.id}/r/${active.revision}/index.html`} sandbox="allow-scripts allow-same-origin"/>:<div className="preview-loading">{!failed&&!interrupted&&<Loader2 className="spin"/>}<p>{failed?'预览准备失败':interrupted?'预览准备已中断':'正在后台构建真实预览…'}</p><p>现在就可以在左侧描述需求开始制作</p>{failed&&<p>{active.initialization.error}</p>}</div>}<div className="phone-home"/></div></div></div>;
}
function Modal({title,subtitle,onClose,children,wide=false}){return <div className="modal-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section role="dialog" aria-modal="true" aria-label={title} className={'modal '+(wide?'wide':'')}><button className="modal-close icon-button" title="关闭" onClick={onClose}><X size={19}/></button><div className="modal-brand"><Sprout size={23}/></div><h2>{title}</h2><p className="modal-subtitle">{subtitle}</p>{children}</section></div>;}
function SettingsModal({current,onClose,onSaved}){
  const [form,setForm]=useState({provider:current?.provider||'deepseek',baseUrl:current?.baseUrl||'https://api.deepseek.com',model:current?.model||'deepseek-flash',apiKey:''}),[pending,setPending]=useState(false),[result,setResult]=useState(''),[failed,setFailed]=useState(false);
  const change=(key,value)=>setForm(f=>({...f,[key]:value}));
  async function perform(action){setPending(true);setResult('');try{const data=await api('/settings'+(action==='test'?'/test':''),{method:'POST',body:json(form)});setFailed(false);if(action==='test')setResult('连接成功，模型可以响应请求。');else onSaved(data);}catch(e){setFailed(true);setResult(e.message);}finally{setPending(false);}}
  return <Modal title="连接你的模型" subtitle="选择一个模型，让小芽帮你实现想法。" onClose={()=>!pending&&onClose()}><div className="provider-options"><button className={form.provider==='deepseek'?'active':''} onClick={()=>setForm(f=>({...f,provider:'deepseek',baseUrl:'https://api.deepseek.com',model:'deepseek-flash',apiKey:''}))}><span className="deepseek-mark">≈</span><div><strong>DeepSeek</strong><small>官方 API</small></div>{form.provider==='deepseek'&&<Check size={16}/>}</button><button className={form.provider==='custom'?'active':''} onClick={()=>setForm(f=>({...f,provider:'custom',apiKey:''}))}><Settings2 size={19}/><div><strong>自定义服务</strong><small>兼容 Chat Completions</small></div></button></div><label>API 地址<input value={form.baseUrl} onChange={e=>change('baseUrl',e.target.value)} placeholder="https://api.deepseek.com"/></label><label>模型名称{form.provider==='deepseek'?<select value={form.model} disabled={pending} onChange={e=>change('model',e.target.value)}>{!deepseekModels.some(m=>m.id===form.model)&&<option value={form.model}>{form.model}（请重新选择）</option>}{deepseekModels.map(m=><option key={m.id} value={m.id}>{m.name} · {m.id}</option>)}</select>:<input value={form.model} onChange={e=>change('model',e.target.value)} placeholder="服务商提供的模型 ID"/>}</label><label>API Key<span className="field-hint">{current?.hasKey?(current.keyStorage?.persisted?'已安全保存 · 同一地址留空保留':'本次启动已设置 · 同一地址留空保留'):(current?.keyStorage?.available?'可安全保存，重开后继续使用':'安全存储不可用或仅本次启动')}</span><input type="password" autoComplete="off" value={form.apiKey} onChange={e=>change('apiKey',e.target.value)} placeholder={current?.hasKey?'••••••••••••••••':'输入你的 API Key'}/></label><div className="security-note"><ShieldCheck size={16}/><span>{current?.keyStorage?.mode==='encrypted'?(current.keyStorage.available?'密钥通过系统安全存储加密保存在本机。正常重开或升级无需重新输入；更换API地址需重新设置密钥。':'系统安全存储不可用，无法保存密钥。请检查系统后重新打开应用。'):'当前运行方式仅在内存保留密钥，退出后需要重新输入。'}对话和项目代码会发送到所选模型服务。</span></div>{result&&<div className={'form-result '+(failed?'failure':'')}>{result}</div>}<div className="modal-actions">{current?.hasKey&&<button className="text-button" disabled={pending} onClick={async()=>{setPending(true);try{const data=await api('/settings/key',{method:'DELETE'});onSaved(data);}catch(e){setResult(e.message);setFailed(true);}finally{setPending(false);}}}>清除密钥</button>}<span/><button className="secondary-button" disabled={pending} onClick={()=>perform('test')}>{pending?<Loader2 size={14} className="spin"/>:<Wifi size={14}/>}测试连接</button><button className="primary-button" disabled={pending} onClick={()=>perform('save')}>保存设置<ArrowUpRight size={14}/></button></div></Modal>;
}
function NewProjectModal({onClose,onCreated}){const [name,setName]=useState(''),[pending,setPending]=useState(false),[error,setError]=useState('');async function create(e){e.preventDefault();setPending(true);try{onCreated(await api('/projects',{method:'POST',body:json({title:name})}));}catch(e){setError(e.message);setPending(false);}}return <Modal title="种下一个新想法" subtitle="描述你的想法，用对话把它变成小程序。" onClose={()=>!pending&&onClose()}><form onSubmit={create}><label>小程序名称<input autoFocus maxLength={40} value={name} onChange={e=>setName(e.target.value)} placeholder="给你的想法起个名字" required/></label><div className="new-template"><div className="tiny-app-icon"><Leaf size={24}/></div><div><strong>从你的想法开始</strong><p>不预设应用功能<br/>告诉小芽你要做什么，随后即可试用</p></div><Check size={18}/></div>{error&&<div className="form-result failure">{error}</div>}<div className="modal-actions"><span className="field-hint">{pending?'正在创建项目…':'创建后即可开始对话，预览将在后台准备'}</span><button className="primary-button" disabled={pending}>{pending?<Loader2 className="spin" size={15}/>:<Plus size={15}/>}创建项目</button></div></form></Modal>;}
function HistoryModal({project,onClose,onRestore}){const [pending,setPending]=useState(''),[error,setError]=useState('');async function restore(id){setPending(id);try{onRestore(await api(`/projects/${project.id}/restore`,{method:'POST',body:json({versionId:id})}));}catch(e){setError(e.message);}finally{setPending('');}}return <Modal title="每一步，都有迹可循" subtitle="恢复旧版本会创建一个新版本，已有记录依然保留。" onClose={()=>!pending&&onClose()} wide><div className="version-list">{[...project.versions].reverse().map(v=><div className="version-row" key={v.id}><div className="version-icon"><History size={17}/></div><div><strong>{v.label}</strong><small>版本 {v.revision} · {new Date(v.time).toLocaleString('zh-CN')}</small></div>{v.revision===project.revision?<span className="current-version">当前版本</span>:<button className="secondary-button" disabled={!!pending} onClick={()=>restore(v.id)}>{pending===v.id?<Loader2 size={13} className="spin"/>:<Undo2 size={13}/>}恢复</button>}</div>)}</div>{error&&<div className="form-result failure">{error}</div>}</Modal>;}
function MemoryModal({project,onClose,onSaved}){const originalChanges=(project.memory?.changes||[]).map(x=>x.text).join('\n');const [goal,setGoal]=useState(project.memory?.goal||project.title),[constraints,setConstraints]=useState(project.memory?.constraints||''),[changes,setChanges]=useState(originalChanges),[error,setError]=useState('');return <Modal title="项目需求" subtitle="这里的要求会持续进入制作上下文。修正不会改变已有代码；恢复旧代码仍保留最新需求。" onClose={onClose}><label>目标<textarea value={goal} onChange={e=>setGoal(e.target.value)}/></label><label>长期约束<textarea value={constraints} onChange={e=>setConstraints(e.target.value)}/></label><label>需求与后续变更（每行一条）<textarea rows={8} value={changes} onChange={e=>setChanges(e.target.value)}/></label>{error&&<p>{error}</p>}<button className="primary-button" onClick={async()=>{try{onSaved(await api(`/projects/${project.id}/memory`,{method:'PUT',body:json({goal,constraints,...(changes===originalChanges?{}:{changes:changes.split('\n').filter(Boolean).map(text=>({text,time:Date.now()}))})})}));}catch(e){setError(e.message);}}}>保存修正</button></Modal>;}
createRoot(document.getElementById('root')).render(<App/>);
